# Seedstack's Main configuration in this file
# See http://seedstack.org/docs/seed/configuration for more information

logging:
  level: INFO

application:
  # Unique identifier of the application across your organization
  id: authProvider
  # Make sure all your application base packages are listed below
  basePackages: [ org.scilab ]
  dataBaseFile: F:/dev/gift-list-bdd/auth/auth.db

jdbc:
  datasources:
    appDataSource:
      url: jdbc:hsqldb:file:${application.dataBaseFile}

jpa:
  units:
    appUnit:
      datasource: appDataSource
      properties:
        hibernate.dialect: org.hibernate.dialect.HSQLDialect
        hibernate.hbm2ddl.auto: update
rest:
  path: api

web :
  server:
    port: 9090

security:
  web:
    urls:
      -
        pattern: /api/**
        filters: [ authcBasic,noSessionCreation ]

  users:
    authAdmin:
      password: ${env.AUTH_ADMIN_PASSWD}
      roles: ADMIN
  roles :
    adminRole: 'ADMIN'
  permissions:
    adminRole: ['adminOps']